version: '3.7'

services:

  users:
    build:
      context: ./services/user_service
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - './services/user_service:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@user_service-db:5432/users_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@user_service-db:5432/users_test
    depends_on:
      - users-db

  users-db:
    build:
      context: ./services/user_service/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
